In [7]:
import pandas as pd

In [8]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print (df)

    Name  Age
0  Alice   25
1    Bob   30

In [12]:
lst =  [['Alice',25],['Bob', 30]]
df = pd.DataFrame(lst,columns=['Name','Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [13]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [14]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [16]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [17]:
df['Name']
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [18]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [19]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [20]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [23]:
df['Gender']=['F','M']
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [42]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
df.drop('Age',axis=1,inplace=True)
print(df.columns)
print(df)

Index(['Name'], dtype='str')
    Name
0  Alice
1    Bob

In [32]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [33]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [43]:
df.fillna

<bound method NDFrame.fillna of     Name
0  Alice
1    Bob>

In [48]:
df['Gender']=['F','M']
print(df)
df.groupby('Gender') ['Age'].mean()

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [56]:
df1=pd.DataFrame({'key':[1,2,],'Name':['Alice','Bob']})

df2=pd.DataFrame({'key':[1,2,],'Age':[25,30]})

result=pd.merge(df1,df2,on='key')
print(result)

   key   Name  Age
0    1  Alice   25
1    2    Bob   30

In [68]:

df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob']
})

df2 = pd.DataFrame({
    'Age': [25, 30]
})

df1.join(df2)

    Name  Age
0  Alice   25
1    Bob   30

In [71]:
df.sort_values('Age')

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [72]:
df['Age'].apply(lambda x:x +1)

0    26
1    31
Name: Age, dtype: int64

In [73]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [74]:
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64